name: Docker CI for Docker Hub Pipeline

on:
  push:
    branches:
      - main
      
jobs:
  docker_build_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: 
          cd frontend && sh docker_frontend.sh ${{ github.run_number }}
          
          cd ../backend && sh docker_backend.sh ${{ github.run_number }}

         
